/*
 * GPIO_INTERFACE.h
 *
 *  Created on: Feb 14, 2020
 *      Author: SemSem
 */

#ifndef GPIO_INTERFACE_H_
#define GPIO_INTERFACE_H_

u32 READPORT(u32 BASE);
u8 READPIN(u32 BASE,u8 PIN);
GPIOERROR WRITEPORT(u32 BASE,u8 VALUE);
GPIOERROR WRITEPIN(u32 BASE,u8 PIN,u8 VALUE);
GPIOERROR SETPORT_DIR(u32 BASE,u8 VALUE);
GPIOERROR SETPIN_DIR(u32 BASE,u8 pin,u8 VALUE);
GPIOERROR ALT_O_GPIO_PORT(u32 BASE,u8 FUNCTION);
GPIOERROR SETCURRENT_PORT(u32 BASE,u8 CRURRENTVALUE);
GPIOERROR SETRES_PORT(u32 BASE,u8 RESISTANCEVALUE);
GPIOERROR DIDITALEN_PORT(u32 BASE,u8 VALUE);




#endif /* GPIO_INTERFACE_H_ */
